import numpy as np
import matplotlib.pyplot as plt

# Ghia et al. (1982) Data for Re=1000
# U-velocity along vertical centerline (x=0.5)
y_ghia_u_ref = np.array([1.00000, 0.97660, 0.96880, 0.96090, 0.95310, 0.85160, 0.73440, 0.61720, 0.50000, 0.45310, 0.28130, 0.17190, 0.10160, 0.07030, 0.06250, 0.05470, 0.00000])
u_ghia_ref = np.array([1.00000, 0.65928, 0.57492, 0.50256, 0.43865, 0.22845, 0.03719, -0.13641, -0.20581, -0.21090, -0.15662, -0.10150, -0.06434, -0.04775, -0.04192, -0.03717, 0.00000])

# V-velocity along horizontal centerline (y=0.5)
x_ghia_v_ref = np.array([1.00000, 0.96880, 0.96090, 0.95310, 0.94530, 0.90630, 0.85940, 0.80470, 0.50000, 0.23440, 0.22660, 0.15630, 0.09380, 0.07810, 0.07030, 0.06250, 0.00000])
v_ghia_ref = np.array([0.00000, -0.05906, -0.07391, -0.08864, -0.10313, -0.16914, -0.22445, -0.24533, 0.05454, 0.17527, 0.17507, 0.16077, 0.12317, 0.10890, 0.10091, 0.09233, 0.00000])

# Simulate loading LBM data from files
# In a real scenario, these files are generated by lbm_mpi_cavity.py
# For this test, we will use Ghia data as a placeholder for LBM output
# to ensure the plotting script works and to show what an ideal match looks like.

# Generate placeholder files similar to what the LBM code would produce.
# This step is only for making this script runnable standalone for testing plot generation.
# The actual files would be generated by the LBM simulation.
placeholder_y_norm = np.linspace(0, 1, 129) # Assuming Ny_global = 129
placeholder_x_norm = np.linspace(0, 1, 129) # Assuming Nx_global = 129

# Interpolate Ghia data onto the LBM grid for placeholder "LBM results"
# This is just to make the example runnable and show a "good" comparison.
# Real LBM data would be used directly.
lbm_u_vertical = np.interp(placeholder_y_norm, y_ghia_u_ref[::-1], u_ghia_ref[::-1]) 
# Ensure Ghia data is flipped for interpolation if y_ghia_u_ref is decreasing
lbm_v_horizontal = np.interp(placeholder_x_norm, x_ghia_v_ref[::-1], v_ghia_ref[::-1])

# Create dummy files as if they were output by the LBM code
u_profile_data_lbm = np.vstack((placeholder_y_norm, lbm_u_vertical)).T
np.savetxt('u_profile_vertical_centerline.txt', u_profile_data_lbm,
           fmt='%.6e', header='y_normalized u_velocity', comments='')

v_profile_data_lbm = np.vstack((placeholder_x_norm, lbm_v_horizontal)).T
np.savetxt('v_profile_horizontal_centerline.txt', v_profile_data_lbm,
           fmt='%.6e', header='x_normalized v_velocity', comments='')


# Load LBM data from the generated .txt files
try:
    lbm_u_data = np.loadtxt('u_profile_vertical_centerline.txt', skiprows=1)
    lbm_y_norm = lbm_u_data[:, 0]
    lbm_u_velocity = lbm_u_data[:, 1]
except IOError:
    print("Error: u_profile_vertical_centerline.txt not found. Ensure LBM simulation was run.")
    lbm_y_norm, lbm_u_velocity = np.array([]), np.array([])


try:
    lbm_v_data = np.loadtxt('v_profile_horizontal_centerline.txt', skiprows=1)
    lbm_x_norm = lbm_v_data[:, 0]
    lbm_v_velocity = lbm_v_data[:, 1]
except IOError:
    print("Error: v_profile_horizontal_centerline.txt not found. Ensure LBM simulation was run.")
    lbm_x_norm, lbm_v_velocity = np.array([]), np.array([])


# Plot U-velocity comparison
plt.figure(figsize=(8, 6))
plt.plot(lbm_u_velocity, lbm_y_norm, 'b-', label='LBM Simulation (Nx=128)', linewidth=2)
plt.plot(u_ghia_ref, y_ghia_u_ref, 'ro', label='Ghia et al. (1982) Re=1000', markersize=6)
plt.xlabel('U-velocity (u/U_lid)')
plt.ylabel('Normalized Y-coordinate (y/L)')
plt.title('U-velocity along Vertical Centerline (x=0.5) at Re=1000')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)
plt.savefig('u_velocity_validation_Re1000.png')
# plt.show()
plt.close()

# Plot V-velocity comparison
plt.figure(figsize=(8, 6))
plt.plot(lbm_x_norm, lbm_v_velocity, 'b-', label='LBM Simulation (Ny=128)', linewidth=2) # x first for horizontal profile
plt.plot(x_ghia_v_ref, v_ghia_ref, 'ro', label='Ghia et al. (1982) Re=1000', markersize=6)
plt.xlabel('Normalized X-coordinate (x/L)')
plt.ylabel('V-velocity (v/U_lid)')
plt.title('V-velocity along Horizontal Centerline (y=0.5) at Re=1000')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)
plt.savefig('v_velocity_validation_Re1000.png')
# plt.show()
plt.close()

print("Validation plots generated: u_velocity_validation_Re1000.png, v_velocity_validation_Re1000.png")
# In a real run, if the LBM files are missing, the plots will be empty or show only Ghia data.
# The placeholder data generation part would be removed.
print("Note: LBM data was simulated using interpolated Ghia data for this script's execution.")
print("In a real validation, ensure LBM output files are present from an actual simulation run.")
